**Random Sampling with Numpy**

In [ ]:
import numpy as np


In [ ]:
import random

**Generate random value**

In [ ]:
np.random.random(1)
# it will print 1d array

array([0.48416892])

In [ ]:
# Now make 2d array by calling previous 1d
np.random.random((3,3))

array([[0.59400779, 0.76972318, 0.29717261],
       [0.46787078, 0.53337157, 0.08701099],
       [0.92114058, 0.61342133, 0.21705228]])

Print integer type value

In [ ]:
np.random.randint(1,4)

2

**4 by 4 array in integer datatype**

In [ ]:
np.random.randint(1,4,(4,4))

array([[1, 2, 3, 3],
       [2, 1, 2, 2],
       [1, 3, 1, 3],
       [3, 3, 3, 3]])